version: '2'
services:
 mysql:
  image: mysql:5.7
  container_name: c_mysql
  environment:
   MYSQL_ROOT_PASSWORD: root
  networks:
   design_net:
    ipv4_address: 172.28.1.3


 wordpress:
  image: wordpress
  container_name: c_wordpress
  ports:
   - 8080:80
  environment:
   WORDPRESS_DB_PASSWORD: root
  networks:
   design_net:
    ipv4_address: 172.28.1.2

networks:
 design_net:
  ipam:
   driver: default
   config:
    - subnet: 172.28.0.0/16
