version: '3'
services:

 db:
  image: mysql:5.7
  container_name: c_mysql
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: wordpress
   MYSQL_USER: DryanLam
   MYSQL_PASSWORD: letmein!
  volumes:
   - /ABC:/var/lib/mysql

  networks:
   internal_net:
    ipv4_address: 172.28.1.3

 app:
  image: wordpress:5.2.3
  container_name: c_wordpress
  ports:
   - 8080:80
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: DryanLam
   WORDPRESS_DB_PASSWORD: letmein!
  networks:
   - internal_net
   - external_net

networks:
 internal_net:
  ipam:
   config:
    - subnet: 172.28.0.0/16
 external_net:
  ipam:
    config:
     - subnet: 192.168.1.0/24
